Repository AY2122S1-CS2103T-T15-3/tp, pull requests merged in 2021-10, with the labels that each got.

#50 Change addressbook to academydirectory in the last few places
  build.gradle
  src/main/java/seedu/academydirectory/model/ModelManager.java
  src/main/java/seedu/academydirectory/ui/UiManager.java
  src/main/resources/images/academy_directory_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/academydirectory/commons/util/AppUtilTest.java
  src/test/java/seedu/academydirectory/logic/commands/ClearCommandTest.java
Labels: type.Bug, priority.Medium

#53 Add Retrieve Command
  src/main/java/seedu/academydirectory/logic/commands/RetrieveCommand.java
  src/main/java/seedu/academydirectory/logic/parser/AcademyDirectoryParser.java
  src/main/java/seedu/academydirectory/logic/parser/RetrieveCommandParser.java
  src/main/java/seedu/academydirectory/model/Model.java
  src/main/java/seedu/academydirectory/model/ModelManager.java
  src/main/java/seedu/academydirectory/model/student/Address.java
  src/main/java/seedu/academydirectory/model/student/Email.java
  src/main/java/seedu/academydirectory/model/student/Information.java
  src/main/java/seedu/academydirectory/model/student/InformationWantedFunction.java
  src/main/java/seedu/academydirectory/model/student/Name.java
  src/main/java/seedu/academydirectory/model/student/Phone.java
  src/test/java/seedu/academydirectory/logic/commands/AddCommandTest.java
  src/test/java/seedu/academydirectory/logic/commands/RetrieveCommandTest.java
  src/test/java/seedu/academydirectory/logic/parser/RetrieveCommandParserTest.java
Labels: type.Story, priority.High

#49 Add Attendance Command
  src/main/java/seedu/academydirectory/logic/commands/AttendanceCommand.java
  src/main/java/seedu/academydirectory/logic/parser/AcademyDirectoryParser.java
  src/main/java/seedu/academydirectory/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/academydirectory/logic/parser/CliSyntax.java
  src/main/java/seedu/academydirectory/logic/parser/ParserUtil.java
  src/main/java/seedu/academydirectory/model/AcademyDirectory.java
  src/main/java/seedu/academydirectory/model/ModelManager.java
  src/main/java/seedu/academydirectory/model/student/Attendance.java
  src/main/java/seedu/academydirectory/model/student/Student.java
  src/main/java/seedu/academydirectory/storage/JsonAdaptedStudent.java
  src/main/java/seedu/academydirectory/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAcademyDirectoryStorageTest/invalidAndValidStudentAcademyDirectory.json
  src/test/data/JsonSerializableAcademyDirectoryTest/duplicateStudentAcademyDirectory.json
  src/test/data/JsonSerializableAcademyDirectoryTest/typicalStudentsAcademyDirectory.json
  src/test/java/seedu/academydirectory/logic/commands/AttendanceCommandTest.java
  src/test/java/seedu/academydirectory/logic/parser/AttendanceCommandParserTest.java
  src/test/java/seedu/academydirectory/model/student/AttendanceTest.java
  src/test/java/seedu/academydirectory/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/academydirectory/testutil/StudentBuilder.java
Labels: type.Story, priority.High

#68 Fix test case bug with ParticipationCommandTest
  src/main/java/seedu/academydirectory/logic/commands/ParticipationCommand.java
  src/main/java/seedu/academydirectory/model/student/Student.java
  src/test/java/seedu/academydirectory/logic/commands/ParticipationCommandTest.java
Labels: type.Bug, severity.Low

#76 Fix bug
  src/main/java/seedu/academydirectory/logic/commands/EditCommand.java
  src/main/java/seedu/academydirectory/logic/commands/GradeCommand.java
  src/main/java/seedu/academydirectory/model/student/Assessment.java
  src/main/java/seedu/academydirectory/model/student/Student.java
  src/test/data/JsonSerializableAcademyDirectoryTest/typicalStudentsAcademyDirectory.json
  src/test/java/seedu/academydirectory/logic/commands/GradeCommandTest.java
Labels: type.Bug, severity.High

#87 Add sort command
  src/main/java/seedu/academydirectory/logic/commands/EditCommand.java
  src/main/java/seedu/academydirectory/logic/commands/SortCommand.java
  src/main/java/seedu/academydirectory/logic/parser/AcademyDirectoryParser.java
  src/main/java/seedu/academydirectory/logic/parser/CliSyntax.java
  src/main/java/seedu/academydirectory/logic/parser/ParserUtil.java
  src/main/java/seedu/academydirectory/logic/parser/ParticipationCommandParser.java
  src/main/java/seedu/academydirectory/logic/parser/SortCommandParser.java
  src/main/java/seedu/academydirectory/model/student/Assessment.java
  src/main/java/seedu/academydirectory/model/student/Name.java
  src/main/java/seedu/academydirectory/model/student/Participation.java
  src/main/java/seedu/academydirectory/model/student/SortableInformation.java
  src/test/java/seedu/academydirectory/logic/commands/SortCommandTest.java
  src/test/java/seedu/academydirectory/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/academydirectory/model/student/AssessmentTest.java
  src/test/java/seedu/academydirectory/model/student/NameTest.java
  src/test/java/seedu/academydirectory/model/student/ParticipationTest.java
  src/test/java/seedu/academydirectory/model/student/SortableInformationTest.java
Labels: type.Story, priority.High

#92 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/logic/commands/attendancecommand/AttendanceCommandSequenceDiagram.puml
  docs/diagrams/logic/commands/attendancecommand/IndexWithinRangeSequenceDiagram.puml
  docs/diagrams/logic/commands/attendancecommand/UpdateModelAttendanceSequenceDiagram.puml
  docs/diagrams/logic/commands/participationcommand/ParticipationCommandMarkAttendanceSequenceDiagram.puml
  docs/diagrams/logic/commands/sortcommand/GetComparatorSequenceDiagram.puml
  docs/diagrams/logic/commands/sortcommand/SortCommandSequenceDiagram.puml
  docs/images/Logic/Commands/AttendanceCommand/IndexWithinRangeSequenceDiagram.png
  docs/images/logic/commands/attendancecommand/AttendanceCommandSequenceDiagram.png
  docs/images/logic/commands/attendancecommand/IndexWithinRangeSequenceDiagram.png
  docs/images/logic/commands/attendancecommand/UpdateModelAttendanceSequenceDiagram.png
  docs/images/logic/commands/participationcommand/ParticipationCommandMarkAttendanceSequenceDiagram.png
  docs/images/logic/commands/sortcommand/GetComparatorSequenceDiagram.png
  docs/images/logic/commands/sortcommand/SortCommandSequenceDiagram.png
Labels: type.Task, priority.High

#96 Update DeveloperGuide.md for GradeCommand and ShowCommand
  docs/DeveloperGuide.md
  docs/images/logic/commands/gradecommand/GradeCommandSequenceDiagram.png
  docs/images/logic/commands/showcommand/ShowCommandSequenceDiagram.png
Labels: priority.High

#102 Fix javadocs for SortCommand
  src/main/java/seedu/academydirectory/logic/commands/SortCommand.java
Labels: type.Bug, severity.Low
